config/routes.rb
GofreerevFb::Application.routes.draw do

  filter :locale

  get "about/index"
  get "about/unsubscribe"
  get 'cookie/decline_cookies'
  get "flickr/index"
  get "linkedin/index"
  get '/auth/:provider/callback', :to => 'auth#create'
  post '/auth/:provider/callback', :to => 'auth#create'
  get '/auth/failure' do
    flash = Flash.new
    flash.message = params[:message] # if using sinatra-flash or rack-flash
    flash.save!
    session[:flash_id] = flash.id
    redirect '/auth'
  end
  get '/auth', :to => 'auth#index'
  get '/auth/index'

  get 'util/new_messages_count'
  post 'util/missing_api_picture_urls'
  post 'util/like_gift'
  post 'util/unlike_gift'
  post 'util/follow_gift'
  post 'util/unfollow_gift'
  post 'util/hide_gift'
  post 'util/delete_gift'
  post 'util/cancel_new_deal'
  post 'util/accept_new_deal'
  post 'util/reject_new_deal'
  post 'util/do_tasks'
  get 'util/currencies'
  post 'util/post_on_wall_yn'
  post 'util/grant_write'
  post 'util/hide_grant_write'
  delete 'auth/destroy'
  post 'util/share_accounts'
  post 'util/share_gift'
  post 'util/open_graph'

  root :to => 'auth#index', :via => :all, :constraints => RoleConstraint.new(:empty, :not_logged_in), :as => 'root1'
  root :to => 'gifts#index', :via => :all, :constraints => RoleConstraint.new(:empty, :logged_in), :as => 'root2'
  root :to => 'facebook#create', :via => :all, :constraints => RoleConstraint.new(:fb_locale, :signed_request), :as => 'root3'
  root :to => 'auth#index', :via => :all, :constraints => RoleConstraint.new(:not_logged_in), :as => 'root4'
  root :to => 'gifts#index', :via => :all, :constraints => RoleConstraint.new(:logged_in), :as => 'root5'

  scope "(:locale)" do
    resources :gifts, :users, :inbox, :comments, :facebook
  end

  

end

app/helpers/users_helper.rb
module UsersHelper

  # document user balance calculation in users/show page (mouse over for balance)
  def gift_balance_calculation_doc(gift, current_user)
    api_gift = gift.api_gifts.find { |ag| [ag.user_id_giver, ag.user_id_receiver].index(current_user.user_id)}
    return nil if !api_gift.user_id_giver or !api_gift.user_id_receiver
    return nil if !gift.price or gift.price <= 0
    # format documentation for balance.
    # one format without currency and exchange rate if exchange rate == 1
    # one format with currency and exchange rate if exchange rate != 1
    # format: new balance yyy user currency = old balance xxx +- (price - negative interest) * exchange rate
    balance_doc = gift.balance_doc(current_user)
    return nil unless balance_doc
    users_currency = @users.first.currency
    exchange_rate1 = ExchangeRate.exchange(1.0, gift.currency, users_currency, gift.received_at)
    exchange_rate2 = ExchangeRate.exchange(1.0, 'USD', users_currency, gift.received_at)
    exchange_rate3 = ExchangeRate.exchange(1.0, 'USD', users_currency, balance_doc[:previous_date])
    return nil unless exchange_rate1 and exchange_rate2 and exchange_rate3
    old_balance_hash = balance_doc[:previous_balance]
    old_balance = (old_balance_hash[BALANCE_KEY] * exchange_rate3).round(2)
    sign_negative_interest = old_balance >= 0 ? '-' : '+'
    # calculate exchange rate gains/losses
    # that is previous_balance + negative_interest in old (date=previous_date) and new (date=received_at) exchange rates
    # calculation is done in current users actual currency
    # note that gains/losses changes if current user selects to see balance in an other currency
    previous_date = balance_doc[:previous_date]
    if previous_date != gift.received_at.to_yyyymmdd
      old_exchange_rates = balance_doc[:previous_exchange_rates]
      new_exchange_rates = balance_doc[:exchange_rates]
      previous_date = balance_doc[:previous_date]
      previous_balance_hash = balance_doc[:previous_balance]
      negative_interest_hash = balance_doc[:negative_interest]
      old_sum = 0.0
      new_sum = 0.0
      previous_balance_hash.keys.each do |currency|
        next if currency == BALANCE_KEY
        logger.debug2  "gift id = #{gift.id}, currency = #{currency}"
        amount = previous_balance_hash[currency] + negative_interest_hash[currency]
        old_sum += ExchangeRate.exchange(amount / old_exchange_rates[currency], 'USD', current_user.currency, previous_date)
        new_sum += ExchangeRate.exchange(amount / new_exchange_rates[currency], 'USD', current_user.currency, gift.received_at)
      end
      gain_loss = new_sum - old_sum
      logger.debug2  "exchange rate gains/losses. gift id #{gift.id}, gain/loss #{gain_loss}"
    else
      gain_loss = 0.0
    end
    # 4 translation key elements: balance_title [, exchange_rate ] [, negative_interest] [, gain/loss] - [, xxx] are optional elements
    # 12 translation keys: balance_title, balance_title_gain, balance_title_loss, balance_title_exchange_rate, balance_title_exchange_rate_gain,
    #                      balance_title_exchange_rate_loss, balance_title_negative_interest, balance_title_negative_interest_gain,
    #                      balance_title_negative_interest_loss, balance_title_exchange_rate_negative_interest,
    #                      balance_title_exchange_rate_negative_interest_gain and balance_title_exchange_rate_negative_interest_loss
    translate_key = ['.balance_title']
    translate_key << 'exchange_rate' if exchange_rate1.round(3) != 1.000
    negative_interest = gift.balance_doc(current_user)[:negative_interest][BALANCE_KEY] || 0.00
    negative_interest = negative_interest * exchange_rate3
    translate_key << 'negative_interest' if negative_interest.round(2) != 0.00
    if gain_loss.round(2) != 0.00
      if gain_loss > 0.00
        translate_key << 'gain'
        sign_gain_loss = '+'
      else
        translate_key << 'loss'
        sign_gain_loss = '-'
        gain_loss = -gain_loss
      end
    end
    translate_key = translate_key.join('_')
    # todo: add more documentation for gain/loss calculation?
    number_of_days = (gift.received_at.to_date - Date.parse(previous_date)).to_i
    t translate_key, # calculation: new_balance = old_balance + price * exchange_rate + negative_interest + currency_gain_loss
                        :new_balance => format_price(gift.balance(current_user, @users.first)),
                        :old_balance => format_price(old_balance),
                        :sign_price => balance_doc[:sign],
                        :price => format_price(gift.price),
                        :exchange_rate => exchange_rate1.round(6),
                        :sign_negative_interest => sign_negative_interest,
                        :negative_interest => format_price(negative_interest),
                        :sign_currency_gain_loss => sign_gain_loss,
                        :currency_gain_loss => format_price(gain_loss),
                        :new_currency => users_currency,
                        :old_currency => gift.currency,
                        :number_of_days => number_of_days
  end # gift_balance_calculation_doc

  # helpers for friends filter and invite friends link
  # shown in one or 2 lines depending on screen width
  def friends_filter_text
    t '.friends_filter_prompt', :appname => APP_NAME, :appname_camelized => APP_NAME.camelize
  end # app_friends_tex

  def app_friends_yes_link (page_values)
    if %w(yes).index(page_values[:friends])
      t('.friends_yes_link_text')
    else
      link_to t('.friends_yes_link_text'), users_path(page_values.merge(:friends => 'yes'))
    end
  end # show_app_friends_link

  def app_friends_no_link (page_values)
    if page_values[:friends] == 'no'
      t('.friends_no_link_text')
    else
      link_to t('.friends_no_link_text'), users_path(page_values.merge(:friends => 'no'))
    end
  end # not_app_friends_link

  def app_friends_all_link (page_values)
    if page_values[:friends] == 'all'
      t('.friends_all_link_text')
    else
      link_to t('.friends_all_link_text'), users_path(page_values.merge(:friends => 'all'))
    end
  end # all_friends_friends_link

  def app_friends_find_link (page_values)
    if page_values[:friends] == 'find'
      t('.friends_find_link_text')
    else
      link_to t('.friends_find_link_text'), users_path(page_values.merge(:friends => 'find'))
    end
  end # all_friends_friends_link

  def app_friends_me_link (page_values)
    if page_values[:friends] == 'me'
      t('.friends_me_link_text')
    else
      link_to t('.friends_me_link_text'), users_path(:friends => 'me')
    end
  end # all_friends_friends_link

  def app_user_filter_text
    t '.app_user_filter_prompt', :appname => APP_NAME, :appname_camelized => APP_NAME.camelize
  end

  def app_user_yes_link (page_values)
    if %w(yes).index(page_values[:appuser])
      t('.app_user_yes_link_text')
    else
      link_to t('.app_user_yes_link_text'), users_path(page_values.merge(:appuser => 'yes'))
    end
  end

  def app_user_no_link (page_values)
    if %w(no).index(page_values[:appuser])
      t('.app_user_no_link_text')
    else
      link_to t('.app_user_no_link_text'), users_path(page_values.merge(:appuser => 'no'))
    end
  end

  def app_user_all_link (page_values)
    if %w(all).index(page_values[:appuser])
      t('.app_user_all_link_text')
    else
      link_to t('.app_user_all_link_text'), users_path(page_values.merge(:appuser => 'all'))
    end
  end

  def api_user_link (provider, page_values)
    if provider == 'all'
      if page_values[:apiname] == 'all'
        t '.api_user_all_link_text'
      else
        link_to t('.api_user_all_link_text'), users_path(page_values.merge(:apiname => 'all'))
      end
    else
      if provider == page_values[:apiname]
        provider_camelize(provider)
      else
        link_to provider_camelize(provider), users_path(page_values.merge(:apiname => provider))
      end
    end
  end



  # user_nav_link is used in users/show nav links - up to 9 links in up to 3 sections
  # nav links is displayed in 1, 2 or 3 lines in users/show page depending on screen width
  # prefix must match prefix for entries in users/user_nav_links in locals
  def user_nav_link (options)
    logger.debug2  "users_helper.user_nav_link: input options = #{options}"
    prefix = options.delete(:prefix)
    symbol = case prefix
               when 'tabs' then :tab
               when 'deal_status' then :status
               when 'deal_direction' then :direction
               else
                 logger.debug2  "error in users/_user_nav_links. user_nav_link must be called with prefix tabs, deal_status or deal_direction"
             end
    page_values = options.delete(:page_values)
    page_value = page_values[symbol]
    array_value = options.delete(:array_value)
    # options.delete(:array_values) # only :array_value is in options hash
    raise "found :array_values" if options.has_key?(:array_values) # todo: remove
    if array_value == page_value
      # inactive link - current tab or current filter value
      t ".#{prefix}_#{page_value}"
    else
      # active link - link to new tab or new filter value
      options = page_values.clone
      options[:id] = @user2.id
      options[symbol] = array_value
      key = ".#{prefix}_#{array_value}"
      logger.debug2  "link key = #{key}, link options = #{options}"
      link_to (t key), user_path(options)
    end
  end # user_nav_link

  # check if Gofreerev is using facebook friend list (FACEBOOK_FRIEND_LIST)
  # and if user has authorized user friend list to Gofreerev ({"permission"=>"user_friends", "status"=>"granted"})
  # must return true or false. used in users.index.fb_friend_list_<boolean> translation
  # display reason why facebook friend list is (almost) empty
  def facebook_friend_list
    return false unless FACEBOOK_USER_FRIENDS
    login_user = @users.find { |u| u.provider == 'facebook' }

app/views/users/_menu_api_user_links.html.erb
<td><%= t '.api_user_filter_prompt' %></td>
<td>
  <% @users.sort_by_provider.each do |login_user| -%>
      <u><%= api_user_link(login_user.provider, @page_values) %></u>
  <% end -%>
  <u><%= api_user_link('all', @page_values) %></u>
</td>

app/views/users/_menu_friends_yes_no_links.html.erb
<td><%= friends_filter_text %></td>
<td>
  <u><%= app_friends_yes_link(@page_values) %></u>
  <u><%= app_friends_no_link(@page_values) %></u>
  <u><%= app_friends_all_link(@page_values) %></u>
  <u><%= app_friends_find_link(@page_values) %></u>
  <u><%= app_friends_me_link(@page_values) %></u>
</td>

app/views/users/_show_balance.html.erb
<%= t ".balance_tab_header_text_html", :username => @user2.short_or_full_user_name(@users) %>
<br/>
<% if (@user2.friend?(@users) <= 2) and @api_gifts.size > 0 -%>
    <div style="width: 100%">
      <table id="gifts" style="border-spacing: 0;">
        <thead>
        <%= render :partial => 'show_balance_header' %>
        </thead>
        <tbody>
        <%= render :partial => 'api_gifts' %>
        </tbody>
        <tfoot>
        <tr id="show-more-rows-spinner">
          <td colspan="9">
            <img src="/images/ajax-loading-64.gif"/>
          </td>
        </tr>
        <tr>
          <td colspan="9">
            <table>
              <tbody id='show-more-rows-errors' class="ajax_errors">
              </tbody>
            </table>
          </td>
        </tr>
        </tfoot>
      </table>
<% end -%>
</div>

app/views/users/_show_friends.html.erb
<%= t ".friends_tab_header_text_html", :username => @user2.short_or_full_user_name(@user) %>
<br/>
<table id="users">
  <tbody>
  <% for user in @users2 do -%>
      <%= render :partial => 'user', :locals => {:user => user} %>
  <% end -%>
  </tbody>
  <tfoot>
  <tr id="show-more-rows-spinner">
    <td colspan="4">
      <img src="/images/ajax-loading-64.gif"/>
    </td>
  </tr>
  <tr>
    <td colspan="4">
      <table>
        <tbody id='show-more-rows-errors' class="ajax_errors">
        </tbody>
      </table>
    </td>
  </tr>
  </tfoot>
</table>

app/views/users/_show_gifts.html.erb
<div style="width: 100%">
  <table id="gifts" style="border-spacing: 0;">
    <thead>
    <%= render :partial => 'gifts/table_header_row' %>
    </thead>
    <tbody>
    <%= render :partial => 'gifts/api_gifts' %>
    </tbody>
    <tfoot>
    <tr id="show-more-rows-spinner">
      <td colspan="4">
        <img src="/images/ajax-loading-64.gif"/>
      </td>
    </tr>
    <tr>
      <td colspan="4">
        <table>
          <tbody id='show-more-rows-errors' class="ajax_errors">
          </tbody>
        </table>
      </td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/users/_user.html.erb
<% edit = false unless edit -%>
<tr>
  <td rowspan="<%= user.app_user? ? 5 : 4 %>" style="width: 102px;"><%= @size = 'large' ; render '/shared/user_div', :user_div => user %></td>
  <td><%= t '.user_name_prompt' %></td>
  <td>:</td>
  <td title="<%= t '.user_name_title', :username => user.short_or_full_user_name(@user), :apiname => user.apiname %>">
    <%= link_to user.camelized_user_name, api_profile_url(user), {:target => '_blank'} %>
  </td>
</tr>
<tr>
  <td><%= t '.friend_status_prompt' %></td>
  <td>:</td>
  <td>
    <%= t user.friend_status_translate_code(@users), user.app_and_apiname_hash.merge(:username => user.short_user_name) %>
  </td>
</tr>
<% if user.app_user? -%>
    <tr>
      <td><%= t '.user_balance_prompt' %></td>
      <td>:</td>
      <td><%= format_user_balance(user, @users) if user.friend?(@user) <= 2 %></td>
    </tr>
    <tr>
      <td><%= t '.last_login_prompt' %></td>
      <td>:</td>
      <td><%= format_user_last_login(user) %></td>
    </tr>
<% else -%>
    <tr title="<%= t 'shared.invite_friend.invite_friend_title', user.app_and_apiname_hash.merge(:username => user.user_name) %>">
      <td><%= t 'shared.invite_friend..invite_friend_prompt' %></td>
      <td>:</td>
      <td><%= invite_friend(user) %></td>
    </tr>
<% end -%>
<tr>
  <td colspan="3">
    <%= render :partial => "friend_action_buttons", :locals => {:friend_action_buttons => user, :edit => edit} %>
  </td>
</tr>
<tr>
  <td colspan="4">
    <hr>
  </td>
</tr>

app/views/users/_user_nav_links.html.erb
<%#
    render user nav links for from an array of valid link values
    object/user_nav_links is an hash with;
    - :prefix: tabs, deal_status or deal_direction
    - :array_values: @tabs, @statuses or @directions
    - :page_values: hash with current page values
-%>

<td><%= t ".#{user_nav_links[:prefix]}_prompt" %></td>
<% user_nav_links.delete(:array_values).each do |array_value| -%>
    <td style="text-decoration:underline;">
      <%= user_nav_link user_nav_links.merge({:array_value => array_value}) %>
    </td>
<% end -%>

app/views/users/_users.html.erb
<% for user in @users2 do loop -%>
    <%= render :partial => 'users/user', :locals => { :user => user } %>
<% end -%>
<%# ajax get more rows -%>
<% if @last_row_id -%>
<tr style="display: none" id='<%= "last-row-id-#{@last_row_id}" %>'><td></td></tr>
<% else -%>
<tr style="display: none"><td></td></tr>
<% end -%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<script>
    // error callback for delete-account - write to debug log + page header
    $(document).ready(function() {
        $("#delete-account").unbind("click") ;
        $("#delete-account").unbind("ajax:error") ;
        $("#delete-account").bind("click", function(xhr, settings){
            // clear page header error messages if any
            clear_flash_and_ajax_errors() ;
        })
        $("#delete-account").bind("ajax:error", function(jqxhr, textStatus, errorThrown){
            add2log('#delete-account::ajax:error');
            add2log('jqxhr = ' + jqxhr);
            add2log('jqxhr.target = ' + jqxhr.target);
            add2log('textStatus = ' + textStatus);
            add2log('errorThrown = ' + errorThrown);
            // inject ajax error message in page header
            add_to_tasks_errors('Error when deleting account: ' + errorThrown + '. check server log for more information.') ;
        })
    })
</script>

<%= t '.page_header_text_html' %>

<table>
  <%= render :partial => 'user', :locals => {:user => @user2, :edit => true} %>
</table>
<br/>
<table>
  <%= render :partial => 'shared/language_tr' %>
  <tr title="<%= t '.currency_title', @user2.app_and_apiname_hash %>">
    <td><%= t '.currency_prompt', @user2.app_and_apiname_hash %></td>
    <td>:</td>
    <td><%= select_tag :user_currency_new2, options_for_select(selected_currency, [@users.first.currency]), {:class => 'user_currency_new', :onchange => 'update_currency(this)'} %></td>
  </tr>
  <tr title="<%= t '.share_balance_title', :appname => APP_NAME %>">
    <td><%= t '.share_balance_prompt', :appname => APP_NAME %></td>
    <td>:</td>
    <td>x</td></tr>
  <tr title="<%= t '.log_out_title', @user2.app_and_apiname_hash %>">
    <td><%= t '.log_out_prompt', @user2.app_and_apiname_hash %></td>
    <td>:</td>
    <td><%= link_to t('.log_out_link_text'), auth_destroy_path(:id => @user2.provider, :return_to => users_path(:friends => 'me')), :method => :delete %></td>
  </tr>
  <tr title="<%= t '.post_on_wall_title', @user2.app_and_apiname_hash %>">
    <td><%= t '.post_on_wall_prompt', @user2.app_and_apiname_hash %></td>
    <td>:</td>
    <td><%= post_on_wall_checkbox(@user2.provider, @post_on_wall) %></td>
  </tr>
  <tr title="<%= t '.access_title', @user2.app_and_apiname_hash %>">
    <td><%= t '.access_prompt' %></td>
    <td>:</td>
    <td><%= link_to @user2.apiname, API_APP_SETTING_URL[@user2.provider] || '#', :target => '_blank' %></td>
  </tr>
  <tr title="<%= t '.delete_account_title', @user2.app_and_apiname_hash %>">
    <td><%= t '.delete_account_prompt', @user2.app_and_apiname_hash %></td>
    <td>:</td>
    <td>
      <%= link_to t('.delete_account_link_text'), user_path(:id => @user2.id), :id => 'delete-account',
                  :remote => true, :format => :js, :method => :delete,
                  :data => { :confirm => t('.delete_account_link_confirm', @user2.app_and_apiname_hash),
                             :type => :script } %>
    </td>
  </tr>
</table>
<br>
<div style="width: 100%"><hr></div>

app/views/users/index.html.erb
<script>
    <%=
      # recheck invalid picture urls with owner permissions
      @missing_api_picture_urls
    %>
</script>

<%# t '.page_header_text_html' %>

<%# responsive user filter menu. 4 lines on small display, 2 lines on medium display and 1 line on big display %>
<br/>
<div style="width: 100%" class="friends-filter-1-line">
  <table>
    <tr>
      <%= render :partial => 'menu_friends_yes_no_links' %>
      <% if @page_values[:friends] != 'me' -%>
          <td>&nbsp;&nbsp;</td>
          <%= render :partial => 'menu_app_user_yes_no_links' %>
      <% end -%>
      <% if @page_values[:friends] != 'me' -%>
          <td>&nbsp;&nbsp;</td>
          <%= render :partial => 'menu_api_user_links' %>
      <% end -%>
      <td>&nbsp;&nbsp;</td>
      <%= render :partial => 'shared/invite_friends_links' %>
    </tr>
    </tr>
  </table>
</div>

<div style="width: 100%" class="friends-filter-2-lines">
  <table>
    <tr>
      <td>
        <table>
          <tr>
            <%= render :partial => 'menu_friends_yes_no_links' %>
          </tr>
          <% if @page_values[:friends] != 'me' -%>
              <tr>
                <%= render :partial => 'menu_app_user_yes_no_links' %>
              </tr>
          <% end -%>
        </table>
      </td>
      <td>&nbsp;&nbsp;</td>
      <td>
        <table>
          <% if @page_values[:friends] != 'me' -%>
              <tr>
                <%= render :partial => 'menu_api_user_links' %>
              </tr>
          <% end -%>
          <tr>
            <%= render :partial => 'shared/invite_friends_links' %>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>

<div style="width: 100%" class="friends-filter-4-lines">
  <table>
    <tr>
      <%= render :partial => 'menu_friends_yes_no_links' %>
    </tr>
<% if @page_values[:friends] != 'me' -%>
    <tr>
      <%= render :partial => 'menu_app_user_yes_no_links' %>
    </tr>
<% end -%>
<% if @page_values[:friends] != 'me' -%>
    <tr>
      <%= render :partial => 'menu_api_user_links' %>
    </tr>
<% end -%>
    <tr>
      <%= render :partial => 'shared/invite_friends_links' %>
    </tr>
  </table>
</div>
<br/>

<%= render :partial => 'shared/language_table' %>
<% if @page_values[:friends] == 'me' -%>
    <%= render :partial => 'shared/share_accounts_dialog' %>
    <%= render :partial => 'shared/share_accounts' %>
    <table width="100%"><tbody id="share_accounts_errors" class="ajax_errors"></tbody></table>
<% end -%>

<% if User.no_app_friends(@users) == 0 -%>
    <%= hr = true ; render :partial => 'shared/no_app_friends' %>
<% end -%>
<% if (@page_values[:apiname] == 'facebook') or (@users.size == 1 and @users.first.provider == 'facebook') -%>
    <div style="width: 100%"><br /></div>
    <div style="width: 100%"><%= t ".fb_friend_list_#{facebook_friend_list}", :apiname => provider_downcase(:facebook), :appname => APP_NAME %></div>
<% end -%>
<div style="width: 100%">
  <table style="width: 100%">
    <thead>
    <tr>
      <td width="1px"></td>
      <td width="1px"></td>
      <td width="1px"></td>
      <td></td>
    </tr>
    <tr>
      <td colspan="4">
        <hr>
      </td>
    </tr>
    </thead>
    <tbody id="users">
    <% for user in @users2 do -%>
        <%= render :partial => 'user', :locals => {:user => user} %>
    <% end -%>
    </tbody>
    <tfoot>
    <tr id="show-more-rows-spinner">
      <td colspan="4">
        <img src="/images/ajax-loading-64.gif"/>
      </td>
    </tr>
    <tr>
      <td colspan="4">
        <table>
          <tbody id='show-more-rows-errors' class="ajax_errors">
          </tbody>
        </table>
      </td>
    </tr>
    </tfoot>
  </table>
</div>

<br/>
<%# add remote link to get more rows and call javascript to setup end of page event and post ajax handling of the new rows. set DEBUG_AJAX to true in initializers/constraints.rb to get more ajax debug information -%>
<%= link_to "show-more-rows",
            users_path(@page_values.merge(:last_row_id => @last_row_id)),
            :remote => true, :data => { :type => :script }, :format => :js,
            :id => "show-more-rows-link", :style => "display: none" %>
<%= render :partial => 'shared/show_more_rows', :locals => {:show_more_rows => 'users'} %>

<hr>

<script>
    // no client side checks before changing currency in this page
    pre_update_currency = default_pre_update_currency;
</script>

app/views/users/index.js.erb
$('#users').append('<%= j render("users", :users => @users2, :last_row_id => @last_row_id) %>');

app/views/users/show.html.erb
<script>
    <%=
      # recheck invalid picture urls with owner permissions
      @missing_api_picture_urls
    %>
</script>

<%= t '.page_header_text_html' %>

<table>
  <%= render :partial => 'user', :locals => {:user => @user2 } %>
</table>
<br/>

<% if @page_values[:tab] -%>

    <%= render :partial => 'user_nav_menu' %>

    <% if @page_values[:tab] == 'friends' -%>
        <%= render :partial => 'show_friends' %>
    <% elsif @page_values[:tab] == 'balance' -%>
        <%= render :partial => 'show_balance' %>
    <% elsif @page_values[:tab] == 'gifts' -%>
        <%= render :partial => 'show_gifts' %>
    <% end -%>

<%# add remote link to get more rows and call javascript to setup end of page event and post ajax handling of the new rows -%>
    <%= link_to "show-more-rows",
                user_path(:id => @user2.id, :last_row_id => @last_row_id, :tab => @page_values[:tab],
                          :status => @page_values[:status], :direction => @page_values[:direction]),
                :remote => true, :data => { :type => :script }, :format => :js,
                :id => "show-more-rows-link", :style => "display: none" if @last_row_id %>
    <%= render :partial => 'shared/show_more_rows', :locals => {:show_more_rows => (@page_values[:tab] == 'friends' ? 'users' : 'gifts')} %>

<% end -%>

<script>
    // no client side checks before changing currency in this page
    pre_update_currency = default_pre_update_currency;
</script>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>